# Generated by Django 2.2.6 on 2020-01-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='send_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(default='', max_length=500)),
                ('from_email', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
