# Generated by Django 2.2.6 on 2020-01-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0002_send_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_email',
            name='from_email',
        ),
    ]
