# Generated by Django 2.2.2 on 2020-01-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0003_remove_send_email_from_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
