# Generated by Django 2.2.2 on 2020-01-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0004_remove_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invalidmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
