# Generated by Django 2.2.2 on 2020-02-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0005_invalidmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
