# Generated by Django 2.2.2 on 2020-02-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0007_auto_20200201_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='send_email',
        ),
    ]
