# Generated by Django 3.1.1 on 2020-09-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0008_delete_send_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='CSV')),
            ],
        ),
    ]
