# Generated by Django 3.1.1 on 2020-09-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0009_csv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSV',
            new_name='email',
        ),
    ]
