# Generated by Django 3.1.1 on 2020-09-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0010_auto_20200925_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('sender_name', models.CharField(max_length=200, null=True)),
                ('sender_email', models.CharField(max_length=200, null=True)),
                ('email_subject', models.CharField(max_length=200, null=True)),
                ('email_list', models.ManyToManyField(null=True, related_name='email_list', to='anees.email')),
            ],
        ),
    ]
