# Generated by Django 3.1.1 on 2020-09-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0011_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='email_list',
        ),
        migrations.AddField(
            model_name='email',
            name='mycampaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anees.campaign'),
        ),
    ]
