# Generated by Django 3.1.1 on 2020-09-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0015_campaign_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='user',
        ),
    ]
