# Generated by Django 3.1.1 on 2020-09-25 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anees', '0016_remove_campaign_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
