# Generated by Django 3.1.1 on 2020-09-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0020_campaign_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='camp',
            field=models.ManyToManyField(null=True, related_name='camp', to='anees.Campaign'),
        ),
    ]
