# Generated by Django 3.1.1 on 2020-09-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0022_auto_20200926_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_camp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anees.campaign'),
        ),
        migrations.AlterField(
            model_name='email',
            name='camp',
            field=models.ManyToManyField(null=True, related_name='camp', to='anees.Campaign'),
        ),
    ]
