# Generated by Django 3.1.1 on 2020-09-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0026_auto_20200926_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_camp',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_camp', to='anees.Campaign'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_email', to='anees.Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='camp',
            field=models.ManyToManyField(null=True, related_name='camp', to='anees.Campaign'),
        ),
    ]
