# Generated by Django 3.1.1 on 2020-09-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0028_auto_20200926_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_camp',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_camp', to='anees.Campaign'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_email', to='anees.Email'),
        ),
    ]
