# Generated by Django 3.1.1 on 2020-09-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0029_auto_20200927_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_camp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_email',
        ),
    ]
