# Generated by Django 3.1.1 on 2020-09-27 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0030_auto_20200927_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='user',
        ),
        migrations.AddField(
            model_name='campaign',
            name='mycustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mycustomer', to='anees.customer'),
        ),
    ]
