# Generated by Django 3.1.1 on 2020-09-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0031_auto_20200927_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='mycustomer',
        ),
        migrations.RemoveField(
            model_name='email',
            name='mycampaign',
        ),
    ]
