# Generated by Django 3.1.1 on 2020-09-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0032_auto_20200927_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
