# Generated by Django 3.1.1 on 2020-09-27 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0033_remove_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
        migrations.AddField(
            model_name='email',
            name='my_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mycust', to='anees.customer'),
        ),
    ]
