# Generated by Django 3.1.1 on 2020-09-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0034_auto_20200927_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='my_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mycustomer', to='anees.customer'),
        ),
    ]
