# Generated by Django 3.1.1 on 2020-09-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0035_campaign_my_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('camp', models.ManyToManyField(blank=True, null=True, related_name='emailings', to='anees.Email')),
            ],
        ),
    ]
