# Generated by Django 3.1.1 on 2020-09-28 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0036_campmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='campmail',
            name='customer_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customermail', to='anees.customer'),
        ),
        migrations.AlterField(
            model_name='campmail',
            name='camp',
            field=models.ManyToManyField(blank=True, null=True, related_name='emailings', to='anees.Email'),
        ),
    ]
