# Generated by Django 3.1.1 on 2020-09-28 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0038_auto_20200928_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campmail',
            name='customer_mail',
        ),
        migrations.AddField(
            model_name='campmail',
            name='campaignings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='anees.campaign'),
        ),
        migrations.AlterField(
            model_name='campmail',
            name='camp',
            field=models.ManyToManyField(blank=True, null=True, related_name='emailings', to='anees.Email'),
        ),
    ]
