# Generated by Django 3.1.1 on 2020-09-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0039_auto_20200928_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='camp_emails',
            field=models.ManyToManyField(blank=True, null=True, related_name='camp_emails', to='anees.Email'),
        ),
        migrations.AlterField(
            model_name='campmail',
            name='camp',
            field=models.ManyToManyField(blank=True, null=True, related_name='emailings', to='anees.Email'),
        ),
    ]
