# Generated by Django 3.1.1 on 2020-09-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0041_auto_20200928_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='camp_emails',
        ),
        migrations.AddField(
            model_name='campaign',
            name='camp_emails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camp_email', to='anees.email'),
        ),
        migrations.AlterField(
            model_name='campmail',
            name='camp',
            field=models.ManyToManyField(blank=True, null=True, related_name='emailings', to='anees.Email'),
        ),
    ]
