# Generated by Django 3.1.1 on 2020-09-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0043_auto_20200928_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campmail',
            name='camp',
            field=models.ManyToManyField(blank=True, null=True, related_name='emailings', to='anees.Email'),
        ),
    ]
